include: package:solid_lints/analysis_options.yaml

dart_code_metrics:
  metrics: 
    cyclomatic-complexity: 40

linter:
  rules:
    lines_longer_than_80_chars: false 
    comment_references: false
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false

analyzer:
  exclude: 
    - "**/messages.dart"