name: Interface ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check flutter sdk version
        working-directory: ./flutter_vlc_player_platform_interface
        run: flutter --version

      - name: Get dependencies
        working-directory: ./flutter_vlc_player_platform_interface
        run: flutter pub get

      - name: Run Solid Lints
        working-directory: ./flutter_vlc_player_platform_interface
        run: dart analyze

      - name: Check formatting
        working-directory: ./flutter_vlc_player_platform_interface
        run: dart format . --set-exit-if-changed

      - name: Run tests
        working-directory: ./flutter_vlc_player_platform_interface
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi
